# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries
name: Release to PyPI
on:
  push:
    tags:
      - v*
permissions:
  contents: read
jobs:
  build:
    uses: ./.github/workflows/build.yml
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Flatten dist folder
        run: |
          mkdir final-dist
          find dist -name '*.whl' -exec cp {} final-dist/ \;
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: final-dist/
